monolog:
    channels:
        - deprecation
        - messenger

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: php://stdout
                level: debug
                channels: ["!event", "!deprecation", "!doctrine", "!messenger"]
#            doctrine:
#                type: stream
#                path: php://stdout
#                level: info
#                channels: [ "doctrine" ]
            messenger:
                type: stream
                path: php://stdout
                level: info
                channels: [ "messenger" ]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!deprecation", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event", "!deprecation"]
            nested:
                type: stream
                path: php://stdout
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            nested:
                type: stream
                path: php://stdout
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!deprecation"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stdout
